projects:
  ronslawnokcGraphQL:
    schemaPath: src/graphql/schema.json
    includes:
      - testModel
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
